steps:
  - name: WebScraper
    type: web_scraper_step
    start_url: https://www.city.arao.lg.jp/
    user_agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 12_6_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.112 Safari/537.36
    output_dir: ./output
    progress_file: ./progress.json
    save_every: 10
    skip_flg: yes
  - name: Xml Law to Json step
    type: xml_law2json_step
    xml_input_dir: ./xml2json/47_kensetsu_juutaku_xml
    json_output_file: ./xml2json/json/47_kensetsu_juutaku.json
    skip_flg: yes
  - name: LLM Tag
    type: llm_tag_step
    input_json_file: ./xml2json/json/min.json
    output_json_file: ./xml2json/taged_json/47_kensetsu_juutaku.json
    llm_url: http://host.docker.internal:11434/v1/
    llm_model: lucas2024/llama-3-elyza-jp-8b:q5_k_m
    llm_api_key: ollama
    llm_prompt_file: ./llm_tag_prompt.txt
    skip_flg: yes
  - name: LLM Tag
    type: llm_tag_step
    input_json_file: ./xml2json/json/47_kensetsu_juutaku.json
    output_json_file: ./xml2json/taged_json/47_kensetsu_juutaku.json
    llm_url: http://host.docker.internal:11434/v1/
    llm_model: schroneko/llama-3.1-swallow-8b-instruct-v0.1:latest
    llm_api_key: ollama
    llm_prompt_file: ./llm_tag_prompt.txt
    skip_flg: yes
  - name: tf-idf Tag
    type: tfidf_tag_step
    input_json_file: ./xml2json/json/47_kensetsu_juutaku.json
    output_json_file: ./xml2json/taged_json/tfidf_47_kensetsu_juutaku.json
    exclude_words: する, ない, から, 及び, この, 又は, に関する, もの, その, による, ある, において,こと,とき
    max_tags: 10
    skip_flg: yes
  - name: Embedding step
    type: embedding_step
    law_catalog_json: ./xml2json/taged_json/tfidf_47_kensetsu_juutaku.json
    embeddings_file: ./xml2json/taged_json/tfidf_47_kensetsu_juutaku_embedding.json
    skip_flg: no
